### PR TITLE
Update articles/cognitive-services/translator-speech/quickstarts/csha…

### PR DESCRIPTION
**Pull request by jmarti326**
…rp.md

Incluyo linea de documentación para que se pueda entender que también se puede utilizar como alternativa VS Code para desarrolladores utilizando Mac OS o Linux.

### CODE REVIEW

**Comment by jmarti326** [comment]
This commit fixes issue #142

**Comment by v-radelg** [comment]
Hello @jmarti326  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by jcmayacu** [comment]
I can use azure maps account "Get Search Address Geocoding" from a web activity of data factories

**Comment by LisandroSu** [comment]
Hello, @jmarti326  ,  Thank you for your feedback and suggestion. 

The English source file has been updated recently. Your feedback was considered when localizing the new version: https://github.com/MicrosoftDocs/azure-docs/pull/18034

Many thanks for your contribution.  

Kind regards,  Microsoft C&E Localization Team

**Pull request closed without merging**
