### PR TITLE
Added missing spaces

### PR DESCRIPTION
**Pull request by gbellmann**
ES: Agregados espacios faltantes.
EN: Added missing spaces.

### CODE REVIEW

**Comment by gbellmann** [comment]
ES: ¿Alguien revisa estas cosas? Es un PR súper simple que podría haber sido aprobado en cuestión de minutos, pero ya lleva 1 mes aquí.

EN: Does anybody review these things? This is a super simple PR that could have been merged in a matter of minutes, but has been here for a month already.

**Comment by gbellmann** [comment]
@srvbpigh: Alguien revisando estos PRs? Anyone checking these PRs?

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by olprod** [comment]
Hello contributor,

Thank you again for your suggestions! We agree with them and we will merge this PR. The suggestion will also be used in the next article update.

Kind regards,

Microsoft DOCS Global Experience Team

**Pull request merged**
